### ISSUE TITLE
Development Branch: Installation ImportError

### ISSUE THREAD

**Issue by BKPetkov** [mcellteam/cellblender#106]
I have no problems installing the master branch releases at various dates from ZIP into Blender.

However when installing the development branch releases, I encounter an error of the following form:

"ImportError: No module named 'cellblender.cellblender_utils'".

This error remains after removal of all CellBlender addons followed by attempted development branch installation and repeated restarting of Blender.

This occurs with Blender Version 2.77 2016-03-18, MCell 3.3 24 Apr 2015, and each CellBlender development branch release attempted. Master branch releases install without issue.

**Comment by cnlbob** [comment]
There are a number of ways that your zip file might have been created. We have a make file that runs a Python script to determine which files belong in the zip file. The command in the makefile is:

  SOURCES = $(shell python cellblender_source_info.py)

That should run they python script named cellblender_source_info.py" which returns a list of all the source files to be included in the zip file. That file does include "cellblender_utils.py", so I'm not sure why that file is not being included in the zip file that you have. Can you unzip the file and post a directory listing of the files at the top level (in the "cellblender" directory)? If so, that might help.

Also, for your information, here are the links to the two files I mentioned in github:

   https://github.com/mcellteam/cellblender/blob/development/makefile
   https://github.com/mcellteam/cellblender/blob/development/cellblender_source_info.py

**Comment by BKPetkov** [comment]
I just now downloaded the latest ZIP from the Development branch of your repository. The same error is given. Must any work be done to the files before Importing to Blender?

Below are the top level files after unzipping:

CHANGELOG.md			cellblender_scripting.py
LICENSE.txt			cellblender_simulation.py
META-INF			cellblender_source_info.py
README.md			cellblender_surface_classes.py
SimControl.c			cellblender_surface_regions.py
SimControl.java			cellblender_utils.py
__init__.py			data_model.py
bng				data_plotters
cellblender_glyphs.py		developer_utilities
cellblender_id.py		git_hooks
cellblender_initialization.py	glyph_library.blend
cellblender_legacy.py		icons
cellblender_main.py		io_mesh_mcell_mdl
cellblender_meshalyzer.py	libMCell
cellblender_mol_viz.py		makefile
cellblender_molecules.py	mdl
cellblender_objects.py		object_surface_regions.py
cellblender_partitions.py	parameter_system.py
cellblender_preferences.py	run_simulations.py
cellblender_project.py		run_wrapper.py
cellblender_reaction_output.py	sim_runner_queue.py
cellblender_reactions.py	test_suite
cellblender_release.py

**Comment by jczech** [comment]
First, here's the tldr to fix your problem:
- unzip cellblender-development.zip
- rename cellblender-development to cellblender (on linux, do this: ``mv cellblender-development cellblender``)
- zip renamed cellblender directory (on linux: `` zip -r cellblender.zip cellblender``)
- now you can install it through Blender like you normally would

Now here's the long explanation of why this is happening if you're interested. CellBlender itself expects its directory name to be cellblender. When you grab the zip file of a specific branch directly from github, it automatically renames the directory by appending a hyphen and the branch name (hence you end up with cellblender-development). When python is importing modules (e.g. import cellblender.cellblender_utils), it can't find cellblender, since it is now cellblender-development.

A second point I should probably mention is that, although the method I outlined for installing CellBlender should work, this is not how we create a zip of CellBlender for regular distribution. There is a makefile in the main cellblender directory that generates the zip file. If you run into other small issues, it might be related to this fact.

**Comment by BKPetkov** [comment]
Thank you, this has fixed my issue. Admittedly a simple one!
