### ISSUE TITLE
LIST based release sites

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mcellteam/cellblender#49]
```
CellBlender does not currently support MCell's list based release sites. This 
can be quite useful if there are many molecules of one type that you want to 
release at specific XYZ locations.

Here is an example of what this looks like in MDL:


Release_Site RELEASE_SITE
{
  SHAPE = LIST
  MOLECULE_POSITIONS
  {
    Molecule
    [.1, .1, .1]
    Molecule
    [.2, .1, .1]
    ...
  }  
}
```

Original issue reported on code.google.com by `czech.ja...@gmail.com` on 14 Apr 2014 at 7:11

**Comment by jczech** [comment]
Here are three possible methods by which a user could create a LIST based release site:

- Create a release at the point where a ray from the cursor intersects with the face. In other words, click on a face and create a release site there.
  - Grabbing the XYZ positions of mouse clicks on faces would be pretty easy, since Blender now drops the 3D cursor at the first ray intersection with a face. There's also some code that illustrates how to do something like this in the Blender text editor under Templates>Python>Operator Modal 3D View Raycast.
- Manually enter XYZ positions
  - Only useful if you have a handful of releases you want to create
- Convert a point cloud of vertices into releases

**Comment by cnlbob** [comment]
Note that this can also be addressed with MDL scripting and/or python scripting.

**Comment by jczech** [comment]
Right. If we really want to get 1.1 out quickly, we could push this feature back to 1.2 since there's a reasonable workaround.

**Comment by cnlbob** [comment]
For 1.1, I think  #94 is done (awaiting confirmation from anyone wanting to check it).

I'm not quite sure what's intended for testing the Geometry importer, so I'm going to look at this one right now. Please advise via email if anyone else is working on it. Thanks.

**Comment by cnlbob** [comment]
I'm planning to start with a list of points that can be added to either by manually adding (and editing) or by clicking a button that adds the point from the 3D cursor. As Jacob pointed out, the 3D cursor snaps to surfaces which can be helpful for placing surface molecules.

Other suggestions are welcome as well!!

**Comment by cnlbob** [comment]
Commit 1f909ca6545542a4f5de5862c3467a3106b8652e (development branch) implements 3 LIST selection mechanisms:

  1. Hand entry of x, y, z
  2. Coordinates of 3D cursor on operator click
  3. All selected points from all selected objects (whether CellBlender model objects or not)

As noted in the commit message, the selected points are not yet stored in the data model nor exported to MDL. This commit only provides the mechanisms to create a CellBlender point list property and fill it.

**Comment by jczech** [comment]
This looks great. Thanks Bob! Maybe you already know this, but it currently only works for volume molecules. If you select surface molecules, it forces you to use an Object/Region based release.

**Comment by cnlbob** [comment]
Thanks Jacob!!!

I hadn't noticed that, but I was just trying to work out the user interface stuff. I'll look into the surface molecule issue and getting it to export as MDL.

**Comment by jczech** [comment]
This seems fairly functional. I suggest closing this and opening any new, related issues as needed. Any objections?
